### ISSUE TITLE
Add GPT Pilot

### ISSUE THREAD

**Issue by mikeslattery** [e2b-dev/awesome-ai-agents#43]
https://github.com/Pythagora-io/gpt-pilot

# 🧑‍✈️ GPT PILOT
### GPT Pilot codes the entire app as you oversee the code being written

---

This is a research project to see how can GPT-4 be utilized to generate fully working, production-ready, apps. **The main idea is that AI can write most of the code for an app (maybe 95%) but for the rest 5%, a developer is and will be needed until we get full AGI**.

**Comment by tizkovatereza** [comment]
Added, thanks! :) Are you founder of GPT Pilot?
