### ISSUE TITLE
Add DB-GPT: The All-In-One Model, Chat Privately With Files Locally, Plugins, Auto Ai Agents, & More!

### ISSUE THREAD

**Issue by csunny** [e2b-dev/awesome-ai-agents#47]
Github Repo: https://github.com/eosphoros-ai/DB-GPT
Sub Module Multi-Agents Repo: https://github.com/eosphoros-ai/DB-GPT-Plugins

DB-GPT-Plugins is a Multi-Agents & Plugins repo for DB-GPT, Can complete various tasks around databases.

**Comment by tizkovatereza** [comment]
Hello, please can you tell more about the DB-GPT? Is it an agent? 
Thanks! :)
