### ISSUE TITLE
Please add the following agents to the list 

### ISSUE THREAD

**Issue by abdshomad** [e2b-dev/awesome-ai-agents#5]
* Noodl https://noodl.net
* Wizard Coder https://github.com/nlpxucan/WizardLM
* Flowize https://github.com/FlowiseAI/Flowise
* LangFlow https://github.com/logspace-ai/langflow 
* Star Coder https://github.com/bigcode-project/starcoder
* Chain Forge https://github.com/ianarawjo/ChainForge
* Eval https://github.com/corca-ai/EVAL

**Comment by mlejva** [comment]
Hi @abdshomad, we'd kindly ask you if you make a PR if you want to add these agents. Thank you!

**Comment by mlejva** [comment]
additionally:
- Flowize is a no-code UI
- LangFlow isn't really an agent but no-code tool for LangChain if I understand the description correctly
- Star Code is a LLM, not an agent
- Chain Forge is "visual programming environment for battle-testing prompts" and not an agent
