### ISSUE TITLE
Links broken  and other major agent frameworks missing 

### ISSUE THREAD

**Issue by dhruvmalik007** [e2b-dev/awesome-ai-agents#53]
Hi, first of all really appreciate the Infographic created by your team. just wanted to create this issue to remind of small issues like:
- some of the links  are broken( **Awesome AI agents SDK** , contact calendly link, etc ).
-  Also in the infographics , I think [Huggingface Agents SDK](https://huggingface.co/docs/transformers/main_classes/agent) is also must needed addition under "Build you own" GPT.

**Comment by tizkovatereza** [comment]
Hello @dhruvmalik007 , I appreciate your feedback a lot! Fixed the links. :) 
Re Huggingface and other frameworks: We are moving the category of frameworks for agents under the Awesome AI Agents SDK, so it is included there already, and I will later probably move the rest of "build your own" category as well.
