### ISSUE TITLE
Add launch date

### ISSUE THREAD

**Issue by vasnt** [e2b-dev/awesome-ai-agents#7]
Awesome list.!!!

Launch date/month may be added to sort out list by date.

**Comment by tizkovatereza** [comment]
Thank you, happy to hear! :)
I considered this, but decided not to for 2 reasons.

1) I don't think it is the right "metric" (lot of these projects are still being improved and evolved, so imho one date of launch is not even saying that much)
2) It may be difficult to track, especially for the closed source projects

Why are you interested in adding launch date?

**Comment by vasnt** [comment]
- Such list normally is reviewed by reader on monthly/weekly basis.  So if i check this repo again on next month, i can easily review tools added last month. 
- if in hurry, Reader are mostly interested going thru latest introduced tools. 

So either date tool added or launch date could be useful.
